### ISSUE TITLE
What loginKey is used for

### ISSUE THREAD

**Issue by aaronfrancis635** [xKiraiChan/emmvrc_detector#1]
I've reverse engineered the whole emmVRC server and API setup so.. yeah

Basically loginKey is sent in all other Auth requests after the first (when it's sent back) as the password. Basically a "remember me" token.

**Comment by xKiraiChan** [comment]
Thank you.

**Comment by aaronfrancis635** [comment]
I added you to a repo on my alt, should have any info you need in it or atleast should help figure out whatever you need.
